name: DevSecOps Security Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Clone OWASP Juice Shop
        run: git clone https://github.com/juice-shop/juice-shop.git

      - name: Run Semgrep SAST
        run: |
          python -m pip install semgrep
          semgrep --config=auto juice-shop

      - name: Run Trivy SCA
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: juice-shop