name: DevSecOps Security Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone OWASP Juice Shop
        run: git clone https://github.com/juice-shop/juice-shop.git

      - name: Run Semgrep (SAST)
  	uses: semgrep/semgrep-action@v1
  	with:
    	  config: auto
    	  target: juice-shop

      - name: Run Trivy (SCA)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: juice-shop